apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1  # Adjust the number of replicas based on your need
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: arifislam/nodejs-cicd:12  # The image you want to deploy
        ports:
        - containerPort: 4000  # This should match the port your Node.js app listens on
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  selector:
    app: nodejs-app
  ports:
    - protocol: TCP
      port: 80  # This is the port the service exposes
      targetPort: 4000  # This is the port your container listens to
      nodePort: 30107  # NodePort that exposes your service externally
  type: NodePort
